- hosts: localhost
  become: true
  roles:
    - ec2
  vars_files:
        - vars/main-aws.yml

- hosts: launched
  become: true
  roles:
    - wordpress
  vars_files:
        - vars/main-aws.yml

- hosts: localhost
  become: true
  roles:
    - rds
  vars_files:
        - vars/main-aws.yml
