---
- name: Launch instance
  amazon.aws.ec2:
    key_name: "{{ ec2inst.key_pair }}"
    instance_type: "{{ ec2inst.inst_flav }}"
    image: "{{ ec2inst.ami }}"
    wait: true
    group_id: "{{ ec2inst.group_id }}"
    count: 1
    vpc_subnet_id: "{{ ec2inst.subnet }}"
    assign_public_ip: yes
    region: "{{ ec2inst.reg_name }}"
    zone: "{{ ec2inst.zone }}"
    state: present
    instance_tags:
        Name: "{{ ec2inst.inst_tag }}"
    aws_access_key: "{{ aws.access_key }}"
    aws_secret_key: "{{ aws.secret_key }}"
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  loop: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  loop: "{{ ec2.instances }}"
